#title: "Fahimeh (Sophia) Nezhadmoghadam"
logo: /assets/img/headshot.jpeg
description: "PhD in computer sience, helllo friendsssss"
#show_downloads: true
theme: jekyll-theme-minimal

# before:
baseurl: "/FNezhadmoghadam/"
# after:
baseurl: ""
